ARG BaseImage
FROM $BaseImage
ENV PYTHONUNBUFFERED 1
WORKDIR /code
COPY . .
EXPOSE 8000
RUN pip install psycopg2==2.8.2 mysqlclient==1.4.2 cx-Oracle==7.1.3 dj-database-url==0.5.0
RUN python manage.py makemigrations polls && python manage.py collectstatic
ARG DjangoSettings=mysite.settings_universal
ENV DJANGO_SETTINGS_MODULE=$DjangoSettings
CMD ["gunicorn", "-c", "gunicorn.ini", "mysite.wsgi"]
